### ISSUE TITLE
Deprecation warning for YAMLLoad

### ISSUE THREAD

**Issue by xoxys** [AndresBott/ansible-autodoc#2]
Hi,

there is a deprecation warning 

```
Annotation.py:275: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(yaml_file)
```

running `Python 3.7.3` on Fedora.

**Comment by alexis-renard** [comment]
Hey, why is this issue closed ? Still have this on `Ubuntu 18.04`, python`3.6.9`.
Seems to have a pull request available [here](https://github.com/AndresBott/ansible-autodoc/pull/6), but it is not merget yet. Almost there !

**Comment by xoxys** [comment]
@alexis-renard I've closed the issue because I got no reaction so far. That's why I've decided to fork this project  to [ansible-doctor](https://github.com/xoxys/ansible-doctor/) and slightly modify it to fit my needs.

Feel free to give it a try, would be happy to get feedback.

**Comment by alexis-renard** [comment]
Ahah, I forked it earlier on to do so as well. Will check out your repo, thanks a lot @xoxys !
Kind of sad that this one is not maintained anymore tho. :disappointed:

**Comment by xoxys** [comment]
Totally agree but I needed a solution and had to go forward :relaxed:
